name: Create PDF report

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: mkdir output
      - uses: docker://dalibo/pandocker:latest
        with: 
          args: "README.md -o output/ppar-haskell-introduction.pdf --toc --pdf-engine=xelatex --template=./eisvogel.latex --listing"
      - uses: actions/upload-artifact@master
        with:
          name: 01-ppar-haskell-introduction.pdf
          path: output
      - uses: docker://dalibo/pandocker:latest
        with: 
          args: "preparation.md -o output/ppar-haskell-preparation.pdf --toc --pdf-engine=xelatex --template=./eisvogel.latex --listing"
      - uses: actions/upload-artifact@master
        with:
          name: 02-ppar-haskell-preparation.pdf
          path: output
